# Generated by Django 4.2.2 on 2023-06-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jurusan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TahunAjaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tahun", models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name="SPP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "jurusan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.jurusan"
                    ),
                ),
                (
                    "tahun_ajaran",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.tahunajaran",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Siswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("kelas", models.CharField(max_length=10)),
                ("nis", models.CharField(max_length=10)),
                (
                    "jurusan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.jurusan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pembayaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("jumlah", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.siswa"
                    ),
                ),
                (
                    "tahun_ajaran",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.tahunajaran",
                    ),
                ),
            ],
        ),
    ]
