# Generated by Django 4.2.2 on 2023-07-01 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_siswa_options_alter_siswa_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siswa",
            options={},
        ),
        migrations.AlterModelManagers(
            name="siswa",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="email",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="password",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="siswa",
            name="username",
        ),
    ]
